name: mbankapp
description: MBANK test app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  device_info_plus: ^11.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.2.1
  flutter_gen: ^5.10.0
  flutter_localizations:
    sdk: flutter
  http: ^1.2.0
  intl: ^0.20.2

  table_calendar: ^3.0.9
  yandex_maps_mapkit_lite: ^4.16.0-beta

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/ic_circle.png
    - assets/pin_green.png
    - assets/pin_red.png
    - assets/pin_yellow.png
    - assets/animation.png
    - assets/ic_dollar_pin.png
    - .env
